name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3.1.4

      - name: Install project
        run: pipenv sync

      - name: Run tests
        run: pytest

